### ISSUE TITLE
Fix first-party modules in `Ruff` configuration

### ISSUE THREAD

**Issue by spietras** [radio-aktywne/template-app-litestar#24]
Should be:

```toml
src = [
  # Allow imports relative to src directory, where the source code lives.
  "src/",
]

[lint.isort]
known-first-party = [
  # Treat tests as a first-party module
  "tests",
]
```
